---
- name: Create User Deployment
  hosts: all
  become: yes
  tasks:
    - name: Create User
      ansible.builtin.user:
        name: deploy
        shell: /usr/bin/bash
    - name: User Belongs to sudoers
      community.general.sudoers:
        name: deploy
        user: deploy
        commands: ALL
    - name: Create SSH Directory
      ansible.builtin.file:
        path: /home/deploy/.ssh
        state: directory
        owner: deploy
        group: deploy
        mode: 0700
    - name: Copy SSH Key
      ansible.builtin.copy:
        src: /home/srvadmin/.ssh/id_rsa_deploy.pub
        dest: /home/deploy/.ssh/authorized_keys
        owner: deploy
        group: deploy
        mode: 0600
