---
- name: Create Group
  ansible.builtin.group:
    name: "{{ group_api }}"
    state: present
    gid: 0777
    
- name: Create User
  ansible.builtin.user:
    name: "{{ user_api }}"
    shell: /bin/bash
    group: "{{ group_api }}"
    home: "{{ var_directory }}"
    uid: 0777

- name: Create Directory "{{ var_directory }}"
  ansible.builtin.file:
   path: "{{ var_directory }}"
   state: directory
   owner: "{{ user_api }}"
   group: "{{ group_api }}"
   mode: '0755'

- name: Copy API file
  ansible.builtin.copy:
    src: /mnt/artifacts/{{ var_artifact }}
    dest: "{{ var_directory }}/{{ var_artifact }}"
    mode: '0644'
    owner: "{{ user_api }}"
    group: "{{ group_api }}"
  register: apiartifact_status

- name: Configure API
  ansible.builtin.template:
    src: api.service.j2
    dest: /usr/lib/systemd/system/api.service
  register: apiunit_status

- name: Enable service
  tags: DEBUG
  ansible.builtin.systemd:
    name: api
    enabled: yes
  register: apienable_status

- name: Start or Restart service
  ansible.builtin.systemd:
    name: api
    state: restarted
    daemon_reload: true
  when: (apienable_status.status.ActiveState != 'active')
    or (apiartifact_status is changed) 
    or (apiunit_status is changed)

